#!/usr/bin/python -B

import os
import sys

from config import *
import utils
import comparator
import normalize


def check_args():
  """Checks the command line arguments.

  Prints a message to standard error if the arguments are incorrect.

  Returns:
    True if the arguments are correct; otherwise False.
  """
  if (len(sys.argv) != 5 or
      not (sys.argv[1] == '-f' and
           sys.argv[3] == '-f' and
           os.path.isfile(sys.argv[2]) and
           os.path.isfile(sys.argv[4]))):
    sys.stderr.write('ERROR Usage: {0} -f <path> -f <path>\n'
                     .format(sys.argv[0]))
    return False
  return True


def main():
  if not check_args():
    sys.exit(1)
  file1 = file(sys.argv[2])
  file2 = file(sys.argv[4])
  if utils.is_mp3(file1.name):
    file1 = normalize.mp3_to_wav(file1.name)
  if utils.is_mp3(file2.name):
    file2 = normalize.mp3_to_wav(file2.name)
  if not (utils.is_wave(file1.name) and utils.is_wave(file2.name)):
    sys.stderr.write(
      'ERROR Usage: input files must be of MP3 or WAVE format\n')
    sys.exit(1)
  file1 = normalize.normalize_wave_file(file1.name)
  file2 = normalize.normalize_wave_file(file2.name)
  (fft1, ceps1) = normalize.get_mfcc(file1.name)
  (fft2, ceps2) = normalize.get_mfcc(file2.name)
  match = (comparator.compare(ceps1, ceps2, MFCC_MATCH_THRESHOLD) or
           comparator.compare(fft1, fft2, FFT_MATCH_THRESHOLD))
  if match:
    print "MATCH"
  else:
    print "NO MATCH"
  file1.close()
  file2.close()


if __name__ == '__main__':
  main()
